name: Test Suite

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Report Coverage
      uses: davelosert/vitest-coverage-report-action@v2
      if: always() && matrix.node-version == '18.x'
      with:
        name: 'Coverage Report'
        # Set reportOnFailure to true in vitest config to generate reports even if tests fail
        json-summary-path: './coverage/coverage-summary.json'
        json-final-path: './coverage/coverage-final.json'

    - name: Upload coverage to artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '18.x'
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30 